N00199023.Web/Models/Categoria.cs
using N00199023.Web.Models;

namespace N00199023.Web.Models
{
    public class Categoria
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
    }
}

N00199023.Web/Models/Cuenta.cs
using N00199023.Web.Models;

namespace N00199023.Web.Models
{
    public class Cuenta
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Categoria { get; set; }
        public string Tipo { get; set; }
        public decimal SaldoInicial { get; set; }
        public string Moneda { get; set; }
    }
}

N00199023.Web/Models/ErrorViewModel.cs
namespace N00199023.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

N00199023.Web/Models/Tipo.cs
using N00199023.Web.Models;

namespace N00199023.Web.Models
{
    public class Tipo
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int IdCategoria { get; set; }
        public Categoria Categoria { get; set; }
    }
}

N00199023.Web/Models/Transaccion.cs
using N00199023.Web.Models;

namespace N00199023.Web.Models
{
    public class Transaccion
    {
        public int Id { get; set; }
        public int IdCuenta { get; set; }
        public Cuenta Cuenta { get; set; }
        public DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public string Tipo { get; set; }
    }
}

N00199023.Web/Controllers/CuentaController.cs
using Microsoft.AspNetCore.Mvc;
using N00199023.Web.Models;
using N00199023.Web.DB;

namespace N00199023.Web.Controllers
{
    public class CuentaController : Controller
    {
        private readonly DbEntities _dbEntities;
        public CuentaController(DbEntities dbEntities)
        {
            _dbEntities = dbEntities;
        }
        public ActionResult Index()
        {
            ViewBag.ListaCuentas = _dbEntities.cuentas.ToList();
            ViewBag.MontoSoles = CalcularTotalSoles();
            ViewBag.MontoDolares = CalcularTotalDolares();
            ViewBag.Conversion = CalcularTotalDolares() * 3.88m;

            return View();
        }
        [HttpGet]
        public IActionResult Crear()
        {
            ViewBag.Tipos = _dbEntities.tipos.ToList();
            return View(new Cuenta());
        }
        [HttpPost]
        public IActionResult Crear(Cuenta cuenta)
        {
            if (cuenta.Tipo == "Efectivo" || cuenta.Tipo == "Tarjeta de Debito") cuenta.Categoria = "Propio";
            else cuenta.Categoria = "Credito";
            _dbEntities.cuentas.Add(cuenta);
            _dbEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Gasto(int IdCuenta)
        {
            ViewBag.CuentaId = IdCuenta;
            ViewBag.Saldo = _dbEntities.cuentas.FirstOrDefault(o => o.Id == IdCuenta).SaldoInicial;

            return View(new Transaccion());
        }
        [HttpPost]
        public IActionResult Gasto(int IdCuenta, Transaccion transaccion)
        {
            Cuenta cuenta = _dbEntities.cuentas.FirstOrDefault(o => o.Id == IdCuenta);
            
            if (cuenta.Tipo != "Tarjeta de Crédito")
            {
                if (cuenta.SaldoInicial >= transaccion.Monto)
                {
                    transaccion.IdCuenta = IdCuenta;
                    transaccion.Tipo = "Gasto";
                    transaccion.Fecha = DateTime.Now;
                    cuenta.SaldoInicial -= transaccion.Monto;
                    _dbEntities.transaccions.Add(transaccion);
                    _dbEntities.SaveChanges();
                    return RedirectToAction("Index");
                }
                else ModelState.AddModelError("Mensaje", "Saldo Insuficiente");
                ViewBag.CuentaId = IdCuenta;
                ViewBag.Saldo = _dbEntities.cuentas.FirstOrDefault(o => o.Id == IdCuenta).SaldoInicial;
                return View("Gasto", transaccion);
            }
            else 
            {
                transaccion.IdCuenta = IdCuenta;
                transaccion.Tipo = "Gasto";
                transaccion.Fecha = DateTime.Now;
                cuenta.SaldoInicial -= transaccion.Monto;
                _dbEntities.transaccions.Add(transaccion);
                _dbEntities.SaveChanges();
                return RedirectToAction("Index");
            } 
        }
        [HttpGet]
        public IActionResult Ingreso(int IdCuenta)
        {
            ViewBag.CuentaId = IdCuenta;

            return View(new Transaccion());
        }

        [HttpPost]
        public IActionResult Ingreso(int IdCuenta, Transaccion transaccion)
        {
            transaccion.IdCuenta = IdCuenta;
            transaccion.Tipo = "Ingreso";
            transaccion.Fecha = DateTime.Now;

            _dbEntities.transaccions.Add(transaccion);
            _dbEntities.SaveChanges();

            Cuenta cuenta = _dbEntities.cuentas.FirstOrDefault(o => o.Id == IdCuenta);
            cuenta.SaldoInicial += transaccion.Monto;
            _dbEntities.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Movimientos(int IdCuenta)
        {
            return View();

        }
        public IActionResult VerGastos(int IdCuenta)
        {
            ViewBag.Gastos = _dbEntities.transaccions
                .Where(o => o.IdCuenta == IdCuenta &&  o.Tipo == "Gasto")
                .ToList();

            return View();
        }
        public IActionResult VerIngresos(int IdCuenta)
        {
            ViewBag.Ingresos = _dbEntities.transaccions
                .Where(o => o.IdCuenta == IdCuenta && o.Tipo == "Ingreso")
                .ToList();

            return View();
        }
        public decimal CalcularTotalSoles()
        {
            List<Cuenta> cuentas = _dbEntities.cuentas
                .Where(o => o.Moneda == "Soles" && o.Tipo != "Tarjeta de Credito")
                .ToList();

            decimal monto = 0.0m;
            foreach (var montos in cuentas)
            {
                monto += montos.SaldoInicial;
            }
            return monto;
        }
        public decimal CalcularTotalDolares()
        {
            List<Cuenta> cuentas = _dbEntities.cuentas
                .Where(o => o.Moneda == "Dolares" && o.Tipo != "Tarjeta de Credito")
                .ToList();

            decimal monto = 0.0m;
            foreach (var montos in cuentas)
            {
                monto += montos.SaldoInicial;
            }
            return monto;
        }
    }   
}

N00199023.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using N00199023.Web.Models;
using System.Diagnostics;

namespace N00199023.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

N00199023.Web/Views/Cuenta/Crear.cshtml
<body>
    <div class="text-center my-3">
        <h1 id="CrearCuenta">Crear Cuenta</h1>
    </div>
    <form action="" method="post">
        <div class="mb-3">
            <label for="Nombre">Nombre: </label>
            <input type="text" class="form-control" Name="Nombre" id="Nombre" value="@Model.Nombre" required>
            @Html.ValidationMessage("Nombre")
        </div>
        <div class="mb-3">
            <label>Tipo: </label>
            <select class="form-select" name="Tipo" id="Tipo">
                <option value="">Seleccione Tipo</option>
                @foreach(var item in (List<Tipo>)@ViewBag.Tipos)
                {
                    if(item.Descripcion == Model.Tipo)
                    {
                        <option value="@item.Descripcion" selected>@item.Descripcion</option>
                    }
                    else
                    {
                        <option value="@item.Descripcion">@item.Descripcion</option>
                    }
                }
            </select>
            @Html.ValidationMessage("Tipo")
        </div>
        <div class="mb-3">
            <label for="SaldoInicial">Saldo Inicial</label>
            <input type="number" class="form-control" Name="SaldoInicial" id="SaldoInicial" value="@Model.SaldoInicial" min="0.00" step="0.01" required>
            @Html.ValidationMessage("Saldoinicial")
        </div>
        <div class="mb-3">
            <label>Moneda: </label>
            <select class="form-select" name="Moneda" id="Moneda">
                <option value="">Seleccione Moneda</option>           
                <option value="Soles">Soles</option>
                <option value="Dolares">Dolares</option>
            </select>
            @Html.ValidationMessage("Tipo")
        </div>
        <div class="text-center my-3">
            <button class="btn btn-primary">Guardar Cuenta</button>
            <a href="/Cuenta/Index" class="btn btn-primary">Atrás</a>
        </div>
    </form>
</body>

N00199023.Web/Views/Cuenta/Gasto.cshtml
<body>
    <div class="text-center my-3">
        <h1 id="Gasto">Nuevo Gasto</h1>
    </div>
        <h1>Saldo: S/.@ViewBag.Saldo</h1>
    <div class="container">
        <form action="/Cuenta/Gasto?IdCuenta=@ViewBag.CuentaId" method="post">
            <div class="mb-3">
                <label for="Descripcion">Nombre del Gasto: </label>
                <input type="text" class="form-control" Name="Descripcion" id="Descripcion" value="@Model.Descripcion" required>
                @Html.ValidationMessage("Descripcion")
            </div>
            <div class="mb-3">
                <label for="Monto">Monto a Gastar: </label>
                <input type="number" class="form-control" Name="Monto" id="Monto" value="@Model.Monto" min="0.00" step="0.01" required>
                @Html.ValidationMessage("Monto")
            </div>
                <button class="btn btn-primary">Guardar Gasto</button>
                <a href="/Cuenta/Index" class="btn btn-primary">Atrás</a>
        </form>
    </div>
</body>

N00199023.Web/Views/Cuenta/Index.cshtml
<body>
    <div class="text-center my-3">
        <h1 id="Finanzas">FINANZAS</h1>
    </div>
    <h1>Cuentas</h1>
    <div class="text-center my-3">
    </div>
    <table class="table table-success table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Categoria</th>
                <th>Tipo</th>
                <th>Saldo</th>
                <th>Moneda</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var cuenta in (List<Cuenta>)ViewBag.ListaCuentas)
            {
                <tr>
                    <td>@cuenta.Id</td>
                    <td>@cuenta.Nombre</td>
                    <td>@cuenta.Categoria</td>
                    <td>@cuenta.Tipo</td>
                    <td>@cuenta.SaldoInicial</td>
                    <td>@cuenta.Moneda</td>
                    <td>
                        <a href="/Cuenta/Gasto?IdCuenta=@cuenta.Id" class="btn btn-primary">Realizar Gasto</a>
                        <a href="/Cuenta/Ingreso?IdCuenta=@cuenta.Id" class="btn btn-primary">Realizar Ingreso</a>
                        <a href="/Cuenta/Movimientos?IdCuenta=@cuenta.Id" class="btn btn-primary">Ver Movimientos</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <h1>Saldo (S): S/.@ViewBag.MontoSoles</h1>
    <h1>Saldo (D): $/.@ViewBag.MontoDolares</h1>
    <h1>El saldo en soles a dolares: S/.@ViewBag.Conversion</h1>
    <h1> </h1>
    <a href="/Cuenta/Crear" class="btn btn-primary">Crear Cuenta</a>
</body>

N00199023.Web/Views/Cuenta/Ingreso.cshtml
<body>
    <div class="text-center my-3">
        <h1 id="Ingreso">Nuevo Ingreso</h1>
    </div>
    <div class="container">
        <form action="/Cuenta/Ingreso?IdCuenta=@ViewBag.CuentaId" method="post">
            <div class="mb-3">
                <label for="Descripcion">Nombre del Ingreso: </label>
                <input type="text" class="form-control" Name="Descripcion" id="Descripcion" value="@Model.Descripcion" required>
                @Html.ValidationMessage("Descripcion")
            </div>
            <div class="mb-3">
                <label for="Monto">Monto a Ingresar: </label>
                <input type="number" class="form-control" Name="Monto" id="Monto" value="@Model.Monto" min="0.00" step="0.01" required>
                @Html.ValidationMessage("Monto")
            </div>
                <button class="btn btn-primary">Guardar Ingreso</button>
                <a href="/Cuenta/Index" class="btn btn-primary">Atrás</a>
        </form>
    </div>
</body>

N00199023.Web/Views/Cuenta/Movimientos.cshtml
<body>
    <div class="text-center my-3">
        <h1 id="Mov">Movimientos</h1>
    </div>
    <div class="container">
        <div class="mb-3">
            <a href="/Cuenta/VerGastos?IdCuenta=@ViewBag.CuentaId" class="btn btn-primary">Ver Gastos</a>
        </div>
        <div class="mb-3">
            <a href="/Cuenta/VerIngresos?IdCuenta=@ViewBag.CuentaId" class="btn btn-primary">Ver Ingresos</a>
        </div>
    </div>
</body>

N00199023.Web/Views/Cuenta/VerGastos.cshtml
<body>
    <h1 id="Gastos">Gastos</h1>
    <table class = "table">
        <thead>
            <tr>

                <th>ID</th>
                <th>Fecha</th>
                <th>Descripcion</th>
                <th>Monto</th>

            </tr>
        </thead>
        <tbody>
            @foreach(var gasto in (List<Transaccion>)ViewBag.Gastos)
            {
                <tr>

                    <td>@gasto.Id</td>
                    <td>@gasto.Fecha</td>
                    <td>@gasto.Descripcion</td>
                    <td>@gasto.Monto</td>

                </tr>
            }
        </tbody>
    </table>
</body>

N00199023.Web/Views/Cuenta/VerIngresos.cshtml
<body>
    <h1 id="Ingresos">Ingresos</h1>
    <table class = "table">
        <thead>
            <tr>

                <th>ID</th>
                <th>Fecha</th>
                <th>Descripcion</th>
                <th>Monto</th>

            </tr>
        </thead>
        <tbody>
            @foreach(var gasto in (List<Transaccion>)ViewBag.Ingresos)
            {
                <tr>

                    <td>@gasto.Id</td>
                    <td>@gasto.Fecha</td>
                    <td>@gasto.Descripcion</td>
                    <td>@gasto.Monto</td>

                </tr>
            }
        </tbody>
    </table>
</body>

N00199023.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Finanzas - N00199023";
}

<div class="text-center">
    <h1 id="Inicio">Examen Final Calidad</h1>
    <h1>1$ = S/.3.88</h1>
    <h1>Usuario: N00199023</h1>
    
</div>

N00199023.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]N00199023</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/N00199023.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">N00199023</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Index">Finanzas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - N00199023.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>